name: deploy to GKE

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: multi-cluster
  GKE_ZONE: us-central1-c

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Build client tests
        run: |-
          docker build -t mejdev/react-test -f ./client/Dockerfile.dev ./client

      -
        name: Run client tests
        run: docker run -e CI=true mejdev/react-test npm test
  
  build-and-push:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    strategy:
      matrix:
        include:
          -
            context: 'client'
            image: 'multi-client'
          -
            context: 'server'
            image: 'multi-server'
          -
            context: 'worker'
            image: 'multi-worker'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build
        run: |-
          docker build \
            -t mejdev/${{ matrix.image }}:latest \
            -t mejdev/${{ matrix.image }}:${{ github.sha }} \
            -f ./${{ matrix.context }}/Dockerfile \
            ./${{ matrix.context }}
      
      -
        name: Push
        run: |-
          docker push mejdev/${{ matrix.image }}:latest
          docker push mejdev/${{ matrix.image }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # This is required for requesting the JWT for gcloud auth
    
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3

    - 
      id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCLOUD_SERVICE_ACCOUNT }}'

    -
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      run: gcloud components install gke-gcloud-auth-plugin

    - 
      name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    
    -
      name: Deploy
      run: |-
        kubectl apply -f k8s
        kubectl set image deployments/server-deployment server=mejdev/multi-server:${{ github.sha }}
        kubectl set image deployments/client-deployment client=mejdev/multi-client:${{ github.sha }}
        kubectl set image deployments/worker-deployment worker=mejdev/multi-worker:${{ github.sha }}
        kubectl rollout status deployment/server-deployment
        kubectl rollout status deployment/client-deployment
        kubectl rollout status deployment/worker-deployment
        kubectl get services -o wide